# Generated by Django 4.2.13 on 2024-05-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_address_profile_organization_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerhours',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
