# Generated by Django 4.2.13 on 2024-08-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_project_location_alter_notification_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
